# Generated by Django 2.1.7 on 2019-02-15 19:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=250)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Gifts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gifts_kind', models.TextField()),
                ('bags_amount', models.SmallIntegerField()),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('is_delivered', models.BooleanField(default=False)),
                ('delivery_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('goal', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('building_number', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('flat_number', models.SmallIntegerField(null=True)),
                ('zip_code', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='PickupAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=6)),
                ('pickup_date', models.DateField()),
                ('pickup_time', models.TimeField()),
                ('comments', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='institution',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='GiveFree.InstitutionAddress'),
        ),
        migrations.AddField(
            model_name='institution',
            name='groups',
            field=models.ManyToManyField(to='GiveFree.Groups'),
        ),
        migrations.AddField(
            model_name='gifts',
            name='delivery_address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='GiveFree.PickupAddress'),
        ),
        migrations.AddField(
            model_name='gifts',
            name='from_who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gifts',
            name='institution',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='GiveFree.Institution'),
        ),
    ]
